### ISSUE TITLE
按下enter显示return

### ISSUE THREAD

**Issue by Alwin233** [mulaRahul/keyviz#18]
win11系统，按下“enter”时，显示“return”
**Version**: 1.0.0

 - Windows11

**Comment by mulaRahul** [comment]
That's actually intentional because the `VkName` (Virtual-Key Name, passed down by windows [VK_RETURN](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes#vk_return)) is `RETURN`. That's why I named it **Return**.

 I know the majority of people, would like to use **Enter** instead of **Return** so I'll apply the same with @mahipa1sinh's PR #19.
