### ISSUE TITLE
Half screen black

### ISSUE THREAD

**Issue by gilforge** [mulaRahul/keyviz#2]
**Describe the bug**
As soon as Keyviz is launched, a black rectangle appears on the bottom half of the screen.
The shortcuts appear anyway.

**Version**: v0.1.0b

**To Reproduce**
1. Execute Keyviz

**Screenshots**
![keyviz_half-screen](https://user-images.githubusercontent.com/21841724/182020685-72fbbabd-8908-4b1e-b01c-7c304a6b4a3d.png)

**Desktop (please complete the following information):**
 - windows 10 Family 20H2, non activated

**Comment by mulaRahul** [comment]
The above behavior may be caused due to this [line](https://github.com/mulaRahul/keyviz/blob/7181648256f55d55163622d26244d950f53f11fb/lib/main.dart#L63), as the `color` is set to `Colors.black`. I've gone ahead and changed that to `Colors.transparent`. Try out this [test-build](https://file.io/5jDtiTaTr3oK) and see whether it fixes the issue or not.

**Comment by gilforge** [comment]
The problem persists. Always this black half-screen.

**Comment by damywise** [comment]
Why not use `WindowEffect.transparent` ?

**Comment by mulaRahul** [comment]
@gilforge I've run Keyviz on a Windows 10 20H2 Home edition and it runs fine -

![win10-20h2](https://user-images.githubusercontent.com/96373135/182152487-493d84c3-756f-42d8-a7b3-9b8bb5ec7230.png)

**Comment by mulaRahul** [comment]
@damywise when I was debugging, setting `effect` as `WindowEffect.transparent` showed some weird artifacts. But now it works fine, will use that instead which may fix @gilforge's issue as well.

**Comment by cquanu** [comment]
How set WindowEffect.transparent?

**Comment by huaiyukhaw** [comment]
Same black rectangle happens to me.

**Comment by huaiyukhaw** [comment]
![image](https://user-images.githubusercontent.com/31930091/182295052-13478ae9-b4af-4017-91f0-12ba31945791.png)

**Comment by mulaRahul** [comment]
Added `WindowEffect.transparent` in the cb2fd4d5a5ce35208e5579328c454a0182091d75. See if it fixes the issue.

**Comment by damywise** [comment]
v1.0.0 has been released. People who have this issue should try it and see if the issue persists

**Comment by gilforge** [comment]
I'm really sorry, but the new version does not fix the bug.
![Capture d’écran 2022-08-02 175053](https://user-images.githubusercontent.com/21841724/182417973-ac661d9e-40b8-4e67-83f1-a1348d270856.png)

**Comment by mulaRahul** [comment]
Another user with the same issue has mentioned that the black screen doesn't appear anymore with the latest version. Because your issues are same, it should work on your end as well.
![black-screen-issue-fix](https://user-images.githubusercontent.com/96373135/182527923-dc30ccc8-5e17-458b-8764-80211de8fb97.png)

Maybe the older version is interfering. Please remove _all_ the versions of keyviz from your computer and then install the latest version and see if the problem persists.

**Comment by mulaRahul** [comment]
Hey @gilforge, please let me know about the results after performing the above.
> Maybe the older version is interfering. @gilforge please remove all the versions of keyviz from your computer and then install the latest version and see if the problem persists.

**Comment by mulaRahul** [comment]
Due to inactivity this issue is closed. Feel free to leave your comments, if you still face the issue.
