### ISSUE TITLE
Three glitches

### ISSUE THREAD

**Issue by Pokem0n2** [mulaRahul/keyviz#28]
Dear Rahul Mula, 
    I love keyviz !!! Many thanks for your work !!!
    Here are three glitches found while using this tiny toolkit :
        1. After unlocking my PC with a password , " Win + L " still shows up on my desktop ;
        2. I'm using a chatting program named WeChat , which contains a " Alt + A "shortcut for snapshot . However , the selecting window of the snapshot function got a higher priority over keyviz , thus keyviz can't pop up ;
        3. Our keyviz doesn't work correctly with any version of AutoCAD , made by Autodesk Inc.
    Look forward to solving these problems , and Best Wishes :-b

**Comment by mulaRahul** [comment]
I'm glad it's helpful to you 🥰!

> 1. After unlocking my PC with a password, " Win + L " still shows up on my desktop

This happens because the **key-down** (key press) events of <kbd>Win</kbd> + <kbd>L</kbd> are passed down, but aren't followed by **key-up** (key release) events. Hopefully, something is wrong with the underlying listener. Also, the same is being tracked here as well #23.

> 2. I'm using a chatting program named WeChat, which contains a " Alt + A "shortcut for snapshot. However, the selecting window of the snapshot function got a higher priority over keyviz, thus keyviz can't pop up

I've seen this happened with normal snapshots using<kbd>Prnt Sc</kbd> or **Print Screen** and tab switching using <kbd>Alt</kbd>+ <kbd>Tab</kbd> as well. Maybe the app's window needs more privileges to draw over the same. Will need to look into the same further.

> 3. Our keyviz doesn't work correctly with any version of AutoCAD , made by Autodesk Inc.

I can't say much about this 🤔, as I've not used that software. It'll be really helpful if you can share some videos/images of the issue.

**Comment by Pokem0n2** [comment]
So HAPPY to hear from U~~
I tried to record a video of the third issue , but keyviz works properly with AutoCAD 2018 now. Then I tried AutoCAD 2004 2010 2020 and 2022 , amazingly , my headache disappeared. lol~ THANX Rahul Mula !!! Thank you so much !!!

**Comment by mulaRahul** [comment]
Great! Thanks for solving a issue 😆!

**Comment by mulaRahul** [comment]
> 1. After unlocking my PC with a password , " Win + L " still shows up on my desktop

As mentioned above, the same happens because the key-press events are not followed by key-up events. Because it's similar to #23, will track it further there.
