### ISSUE TITLE
Add the adjustment of the background transparency of the button display and resize the button display to a smaller size

### ISSUE THREAD

**Issue by Copy2Translator** [mulaRahul/keyviz#38]
I really like this software of yours and I appreciate your efforts！

I would like you to add transparency adjustment for the background of the display button and also resize to a smaller size? The current 32px still seems a bit too big sometimes.

Also, if you press the spacebar first and then press other function keys at the same time, they are not displayed at the same time, but are replaced by other keys. I would like them to be displayed at the same time when you press the spacebar first and then press the other function keys at the same time.

https://user-images.githubusercontent.com/75414580/186556095-611132f5-2b05-4086-905c-66346cb40f80.mp4

**Comment by mulaRahul** [comment]
## More Size Options & Border Transparency [✨Enhancement]
Someone else also requested to add more _smaller_ size options in #14. I think I should replace the **dropdown** with a **slider** with **16px** as the lower limit and **64px** as the upper limit. The **border transparency** can be added along with the above change.

## Non-[Modifier](https://github.com/mulaRahul/keyviz/blob/7b67b13a8516b7dfe5f3415e5d696949ede5fff0/lib/data/keymaps.dart#L14) Key Combinations gets Replaced [🐛Bug]
Indeed, if <kbd>Space</kbd> (or any other _non-modifier_ key) is pressed together with another key, the former gets replaced. The expected behavior should be  - every pressed key being visualized together.

**Comment by Blender-S** [comment]
Looking forward to the update, thanks again!

**Comment by mulaRahul** [comment]
> Non-Modifier Key Combinations gets Replaced [🐛Bug]

is now fixed with this commit 01da6fc9e55d107f47a17be203ea2426b28b1e76 and [v1.0.6](https://github.com/mulaRahul/keyviz/releases/tag/v1.0.6).

https://user-images.githubusercontent.com/96373135/187074505-a8875e21-ea81-4ece-ae97-6091b533dce8.mp4

As for **More Size Options & Border Transparency**, you can add your suggestions in #14.
