### ISSUE TITLE
Pop Context Menu on Left Click

### ISSUE THREAD

**Issue by WHYBBE** [mulaRahul/keyviz#39]
**Describe the bug**
任务栏的菜单需要用左键呼出，和其他软件的行为不太一致，不符合使用习惯
比如Windows Defender使用左键呼出软件，右键呼出菜单
也可以像蓝牙那样，左右键都可以呼出菜单
PowerToys是双击左键呼出软件，右键呼出菜单

所以可以左键呼出软件的设置，右键呼出小菜单

**Version**: About里是v1.0.0，压缩包是v1.0.2，安装包名是v1.0.1（所以我也不知道是哪个版本）

**Desktop (please complete the following information):**
 - Windows 11

**Comment by mulaRahul** [comment]
## Pop-up Context Menu
Indeed popping up the context menu by right-clicking the tray icon will be a more consistent UX. About the left click, I think it would be better to pause/resume the visualizer instead of showing the settings. What are your thoughts?

## Versioning Blunder
Well ...I forgot to edit the version numbers in the about page (code) 😅. I'll get it fixed.

**Comment by WHYBBE** [comment]
Sorry, because there're a lot of issues written in Chinese, I overlooked that you are an English speaker.

The left-clicking is not commonly used, and adding some functions to the left-clicking would not violate the "Principle of least astonishment". So as long as you keep a certain function unchanged in later versions, it is acceptable. But the function of the right button should be arranged first.😋

Thank you!

**Comment by mulaRahul** [comment]
The context menu can now be popped up by **right-clicking** on the tray icon a533d9d8a873505ff6459e4dea6a0d16d4bb475c. And by **left-clicking**, you can pause/resume the visualizer a533d9d8a873505ff6459e4dea6a0d16d4bb475c.

https://user-images.githubusercontent.com/96373135/187074903-dde38e4b-3a0f-4de6-a045-7ecca393d062.mp4
