### ISSUE TITLE
Portable releases don't include necessary dll to run

### ISSUE THREAD

**Issue by shirok1** [mulaRahul/keyviz#48]
**Version**: v1.0.4

![image](https://user-images.githubusercontent.com/12044683/188296608-00d5f90a-364b-4c77-aa2a-181db74256ab.png)

**Comment by mulaRahul** [comment]
The portable release is created with third-party software [Enigma Virtual Box](https://enigmaprotector.com/en/aboutvb.html) and it doesn't guarantee to work in every system. You're getting the error because it couldn't find a **.dll** file. It may have been caused due to some issue during unpacking the zip, or maybe not. 

I'll recommend you to use the installer first and then use software like **_Enigma Virtual Box_** to create a portable **.exe** for your system.

**Comment by shirok1** [comment]
I suggest that "portable" releases should be a flat archive instead of a self-extracting program. Such format is very suitable for external package management like scoop.

**Comment by mulaRahul** [comment]
A flat archive isn't possible with flutter's build. The build contains many directories and sub-directories which are referenced by the framework itself.

![image](https://user-images.githubusercontent.com/96373135/188302787-20a87863-7cc3-4b1f-b749-24bd3a2e0669.png)

**Comment by shirok1** [comment]
> The build contains many directories and sub-directories which are referenced by the framework itself.

Not a problem. Package management like scoop are born to manage such directories. On the opposite, the so-called "portable .exe" simply extract them to `%TEMP%` every time you start them.

Last but not least, Enigma Virtual Box is a proprietary software, and it doesn't work well.

**Comment by mulaRahul** [comment]
I'm not familiar with **_scoop_**, so need to check about the same first.

**Comment by damywise** [comment]
I can reproduce this issue by specifically not including the .dll when using Enigma Protector. I don't know much past that.
