### ISSUE TITLE
Windows Defender detects Backdoor:Win32/Bladabindi!ml

### ISSUE THREAD

**Issue by jpyrat** [mulaRahul/keyviz#60]
**Describe the bug**
Détecté : Backdoor:Win32/Bladabindi!ml
Détails : Ce programme fournit un accès à distance à l’ordinateur sur lequel il est installé.

**Version**: v1.0.6

**To Reproduce**
1. with Google Chrome (last version, on Win 11 22H2)
2. Visit https://github.com/mulaRahul/keyviz/releases/download/v1.0.6/keyviz-v1.0.6.zip
3. Fail : virus detected
4. See error in history of windows defender

**Expected behavior**
No virus ;-).

**Screenshots**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/763100/193788179-7191b491-74d9-4f27-b289-841e26800fa9.png">

**Desktop (please complete the following information):**
 - Windows 11 22H2

**Comment by mulaRahul** [comment]
Yep, you're right! 

The biggest issue in the current release is the security warning message. Because the software isn't signed with a trusted (paid-Microsoft) certificate, and it reads keyboard inputs -  obviously it's regarded as a trojan by the system. You can read further on the same in this #11 discussion.

I understand your concern, and that's why I've planned to solve the same in the next release. I'll purchase a Microsoft license, sign the executable with their certificate and then release the same, preferably on the Microsoft store as well.
