### ISSUE TITLE
Displaying key combinations exactly in accordance with my keyboard layout

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [mulaRahul/keyviz#63]
**Describe the bug**
It does not detect the keyboard layout of the operating system. It always shows results only for English characters. For example, my keyboard is Turkish-Q and the letters on the right are showing incorrectly.

**Version**: v1.0.6

**To Reproduce**
1. Go to 'Windows Language & region settings.'
2. Go to 'Your language options'
3. Click "Add a keyboard"
4. Add Turkish-Q keyboard layout. (It is representative.)
5. Change keyboard layout with Win+Space keystroke.
6. In this combination: CTRL + ALT + ü to (~). Keyviz show this keystroke: (Image 1)
7. See error

**Expected behavior**
It must display key combinations exactly in accordance with my keyboard layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/53148314/204255857-7c848c05-2d45-4923-a002-10d921507856.png)
(Image 1)

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by mulaRahul** [comment]
Hello @ahmet-cetinkaya, it doesn't detect anything because there is nothing like that for now 😅. As the project is in its earlier stages, I've only developed it around the English keyboard (_which I use_). 

Multi-Keyboard Support will be added in the upcoming version along with cross-platform support. You can also check out discussion #16 for the same.

**Comment by ahmet-cetinkaya** [comment]
Thank you. You are right, it would be more correct to open a feature request issue. I think a issue was opened before, the search yielded no results. #16 has expressed a similar request, so I can close this issue. 🙂
