### ISSUE TITLE
Settings are stored under AppData\Roaming\com.example\keyviz

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [mulaRahul/keyviz#69]
**Describe the bug**

Program settings are saved in: `C:\Users\<userprofile>\AppData\Roaming\com.example\keyviz\shared_preferences.json`

`com.example` clearly being a placeholder.

**Version**: v1.0.6

**To Reproduce**
1. Save app config, find filepath mentioned above

**Expected behavior**

Should not use `com.example` in file path

**Desktop (please complete the following information):**
 - Windows 10

**Comment by mulaRahul** [comment]
Hello @Mario-Hofstaetter, the configuration data/JSON is handled by [shared-preferneces](https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences). The `com.example` is a conventional thing (_though `example` should be `keyviz.mulaRahul` instead_). 

In the next release, I'll use custom data storage instead of shared prefs so it won't be an issue by then.

**Comment by mulaRahul** [comment]
Shared Preferences aren't used anymore.
